### PR TITLE
Simplify README instructions by removing need for GitHub Desktop

### PR DESCRIPTION
**Pull request by thatlittlegit**
I'll need you guys to verify that the steps still work; however, this negates the need to install GitHub Desktop and create an account with GitHub. I also did some minor Markdown reformatting.

### CODE REVIEW

**Comment by sprkeper** [comment]
yeah i tried this and i ended up with no mods to select when i opened up hoi4, or i might be doing it wrong

**Comment by sprkeper** [comment]
fixed it by changing the **path="mod/big-europe-dev/"** in the _Big Europe Dev version.mod_ file
to:
**path="C:\Users\(username here)\Desktop\Documents\Paradox Interactive\Hearts of Iron IV\mod\big-europe-dev-master"**

works for me now, not sure if it'll work for everyone though.

**Comment by thatlittlegit** [comment]
That's odd. I'll look into it.

**Comment by thatlittlegit** [comment]
@sprkeper Can you take another look at it? It should be fixed now.

**Comment by sprkeper** [comment]
tested it again, but i’ve had to change the Documents/Paradox Interactive/Hearts of Iron IV/mod to C:/Users/(my name)/Documents/Hearts of Iron IV/mod to actually show up on my game, but it keeps crashing for me; not really sure why

I think someone else should test this as well

**Comment by thatlittlegit** [comment]
Adding the `C:\Users\(name)\` was supposed to be implied; I figured it was a bit long to type all of that into the README, although I just realized I only have to say it once, so it isn't a big deal.

It crashing your game, though, is not something I expected at all. I agree, someone else should test it.

**Pull request merged**
